hexo:
    container_name: hexo_existing_blog
    build: .
    dockerfile: ./hexo.dockerfile
    command:  hexo server -p 5000 --debug --draft
    ports:
        - "5000:5000"
    volumes:
            - ./blog/:/blog/
            - ./generate/:/blog/public/
